### ISSUE TITLE
[LocationProvider] FreeGeoIP has shutdown

### ISSUE THREAD

**Issue by Jord-JD** [DivineOmega/php-geolocation#1]
The FreeGeoIP service has shutdown and has been replaced.

A new location provider should be created for the replacement and the old service provider should throw a deprecated exception.

More info:

* http://freegeoip.net/shutdown
* https://github.com/apilayer/freegeoip#readme

**Comment by milo526** [comment]
I'd like to start working on this and switch the `FreeGeoIP` provider over to an apilayer one.

**Comment by Jord-JD** [comment]
Hi Milo. Thanks for offering to help. Feel free to fork this repo and work on an apilayer location provider.

If you need any help, give me a shout. :slightly_smiling_face:

**Comment by Jord-JD** [comment]
Fixed by @milo526 in #2.
