### ISSUE TITLE
Move Examples from src folder

### ISSUE THREAD

**Issue by peter279k** [DivineOmega/php-geolocation#3]
As title, I think the `Examples` folder should not be in the `src` folder.
I think we should move this to the root folder.

**Comment by Jord-JD** [comment]
I'm curious why you think `Examples` should be outside of the `src` folder?

**Comment by peter279k** [comment]
I think the `Examples` is not part of the `src` folder so it should be outside of the `src` folder.

**Comment by peter279k** [comment]
Well, I think it's okay to let the `Examples` folder in `src` folder finally.

This issue should be closed :-).
